### PR TITLE
Trigger github actions when PR is made against develop

### PR DESCRIPTION
**Pull request by anoronh4**
Linting, pytests, etc are configured to run when changes are made against master. Since for our fork we are planning to push changes to develop, I thought it might be a good idea to trigger the same workflows when PRs are made against the develop branch. This should help automate and ensure consistent testing and code formatting.

### CODE REVIEW

**Comment by buehlere** [comment]
Hi @anoronh4 this is a great idea! 

One thing to note is that these changes might cause conflicts with `nf-core/modules`, although they're simple enough it might not be a problem.

I guess another option would be to copy the gitaction workflows and edit them to run on PR to develop. For example, we would have a workflow called:`code-linting-develop.yml` that runs when we open a PR to develop. 

I'm fine with trying either! Let me know your thoughts.

**Comment by anoronh4** [comment]
> I guess another option would be to copy the gitaction workflows and edit them to run on PR to develop. For example, we would have a workflow called:`code-linting-develop.yml` that runs when we open a PR to develop.

I was thinking about this solution as well. it makes sense to keep them separate in case of conflicts.

**Comment by anoronh4** [comment]
i disabled tests for sentieon modules in the new github workflow files, so a PR against develop will not trigger a sentieon test even if a change in those modules are detected. But they are still enabled in the original workflow files, meaning the tests may still trigger when a PR is made against master (and potentially during a sync-fork action). I wonder if this will lead to any issues down the line, or if we can bypass any branch protections in case of a check failure.

**Comment by buehlere** [comment]
> i disabled tests for sentieon modules in the new github workflow files, so a PR against develop will not trigger a sentieon test even if a change in those modules are detected. But they are still enabled in the original workflow files, meaning the tests may still trigger when a PR is made against master (and potentially during a sync-fork action). I wonder if this will lead to any issues down the line, or if we can bypass any branch protections in case of a check failure.

I'm not super familiar with sentieon, but I see it has some special secret files and is likely an enterprise product. The only problem I can think of right now is that our pytest workflow might fail on master if that module is changed. However, I think that's something we can probably keep an eye out for and won't cause any major issues.

**Review by buehlere — APPROVED** [review]
I think this looks good! There is a lingering question or two concerning the sention module, but I think this should work pretty well.

**Pull request merged**
